version: '3'
services:

  postgres:
    image: postgres:16.3
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - remo

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - remo

volumes:
  postgres:
    driver: local

networks:
  remo:
    driver: bridge
