name: CI Pipeline

on:
  push:
    branches: ['main', 'dev', 'setup/ci-cd']
  pull_request:
    branches: ['main', 'dev', 'setup/ci-cd']

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            cd ./remo-deployment
            bash ./deploy.sh
