name: CI Pipeline

on:
  push:
    branches: ['main', 'dev', 'setup/ci-cd']
  pull_request:
    branches: ['main', 'dev', 'setup/ci-cd']

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-docker-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image name
        id: image_name
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/remo-be:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.image_name.outputs.IMAGE_NAME }}

      - name: Logout from Docker Hub
        run: docker logout
